Ghi 14/tyrant switching
prelusion/XSLiveCommands pull request #32
Opened 2024-01-15 12:21 UTC by prelusion

2024-01-15 17:18 UTC, Divy1211 requested changes

2024-01-15 17:18 UTC, Divy1211 commented on Client/src/renderer/src/components/DisconnectButton.vue
Change to sharp corner for leave button for consistency with the rest of the app's buttons:
![image](https://github.com/prelusion/XSLiveCommands/assets/20875997/048f20a1-8b66-4a0e-8edd-576062afae99)

2024-01-15 17:18 UTC, Divy1211 commented on Client/src/renderer/src/components/DisconnectButton.vue
Change disconnect button corners to be sharp, for consistency with the rest of the App:
<img src="https://github.com/prelusion/XSLiveCommands/assets/20875997/eb1df0c6-b6db-4592-a8b9-ad7660639ef8" width=50% height=50%>

2024-01-15 17:18 UTC, Divy1211 commented on Client/src/renderer/src/components/modal/CustomModal.vue
- Change rounded corners to sharp corners on the dialogue box, on the text field, on the button.
- Add a black outline to the dialogue box for slightly better visibility?
- "Room **p**assword" -> "Room **P**assword"
- Change password input field width/height to match the other text fields in the app
- Change "Lets Tyrant" button size to match "Join as Tyrant" and other buttons
- Move "Lets Tyrant" button to bottom left
- Add "Cancel" button to bottom right (I found out that clicking away/pressing esc closes the modal, but I was confused for a bit on how to before I figured it out 11)

- Suggestion: "Lets Tyrant" -> "Begin Tyranny!"
- Suggestion: "Room Password" -> "Launch Code" (also rename password in create menu to "Launch Code"? 😝)

<img src="https://github.com/prelusion/XSLiveCommands/assets/20875997/ee7b3c7b-7d7f-45a8-846b-ff88ee9b1aeb" width=50% height=50%>

2024-01-15 17:18 UTC, Divy1211 commented on Client/src/renderer/src/components/windows/CommandCentre.vue
- Move the "Stop the Tyranny" button so that it replaces the "Join as Tyrant"

- Suggestion: "Join as Tyrant" -> "Begin Tyranny"
- Suggestion: "Stop the Tyranny" -> "End Tyranny" (begin vs end are opps)

<img src="https://github.com/prelusion/XSLiveCommands/assets/20875997/c071bf96-658c-4bb3-80a0-fb9fe0b5b3bf" width=50% height=50%>

2024-01-15 17:29 UTC, KSneijders commented on Client/src/renderer/src/components/windows/CommandCentre.vue
Delano had the button in the bottom right but I said that I'd prefer if we create a default of exit-like buttons in top right instead. I didn't intend for a text button but it's to clearly communicate the difference between actions and disconnect. It's not perfect but at least for me, I click buttons out of intuition and many times don't read them (ofc my problem). But in this app (like DE) I click on disconnect buttons because they're sometimes on the right, sometimes on the left. Or if all are on the right, sometimes non exit buttons are on the right too. Keeping it confusing in my opinion. @Divy1211 Thoughts?

2024-01-15 17:33 UTC, Divy1211 commented on Client/src/renderer/src/components/windows/CommandCentre.vue
7 I get the reasoning behind it now yea

I think if we had a picture button, then yes it'd make sense to have it in the top right 100% like the dc button.

Although with just a picture, we'd need to do good icon design to communicate what the button means, and since "stopping tyranny" is not universally associated with an icon (unlike leave/hamburger menus) imo we should actually keep the text button (and hence the suggested move to bottom right)

Another suggestion for the future is to colour the text buttons so the reading is minimised and people can just associate the colour with the action

2024-01-15 18:15 UTC, prelusion commented on Client/src/renderer/src/components/modal/CustomModal.vue
Can you check if it's correct now?
![image](https://github.com/prelusion/XSLiveCommands/assets/43753957/218b6bf7-3c41-44f1-8cb4-df82543e4bd2)

2024-01-15 18:33 UTC, Divy1211 commented on Client/src/renderer/src/components/modal/CustomModal.vue
Looking fantastic, thanks so much for the changes!

2024-01-15 21:28 UTC, KSneijders commented on Client/src/renderer/src/components/windows/CommandCentre.vue
@Divy1211 Well, that's kind of why I talked about merging the two views, that might simplify the view a bit.

That being said, maybe coloured buttons could solve it. 
If so, we really need to start thinking about design

2024-01-15 22:23 UTC, KSneijders commented on Client/src/renderer/src/components/modal/content/Password.vue
The improvements definitely look nice. I have a couple small remarks if we do mention style. 
Buttons aren't 100% squared off, they have a border radius of maybe 3px or so, maybe add that to the modal & buttons and inputs (see first and last image). 
Also the hover colour on the buttons is a lot more 'visible' than other buttons in our app (see first 2 images). 

![image](https://github.com/prelusion/XSLiveCommands/assets/32707500/da636008-1e32-445c-8869-4ed0805f5166)
![image](https://github.com/prelusion/XSLiveCommands/assets/32707500/126ab42c-21d4-4e38-b871-76ed64b054f4)
![image](https://github.com/prelusion/XSLiveCommands/assets/32707500/5378cab2-aa80-493a-a16f-4b3fb8540120)

2024-01-16 16:55 UTC, prelusion commented on Client/src/renderer/src/components/modal/content/Password.vue
This should be fixed now

2024-01-16 22:47 UTC, KSneijders approved these changes

2024-01-17 00:49 UTC, KSneijders commented
Need to test this PR in-game. Should be a requirement for all bigger PRs
Especially if they change networking behaviour

2024-01-17 15:28 UTC, Divy1211 commented on Client/src/renderer/src/components/windows/CommandCentre.vue
Merging the views means an additional click on the same button to leave the room for tyrants, which is confusing, imo. I do think keeping a text button for any non universal buttons with standard icons is the way to go

2024-01-17 21:09 UTC, merged